from config import *

# Display
CAMERA_SIZE = [ WINDOW_SIZE[0], WINDOW_SIZE[1] ]

# Map
TILE_IMAGE = 0
TILE_WALKABLE = 1
TILE_SLICE = 2
TILE_SIZE = 3
TILE_POS = 4

# Layers:
LAYER_DATA =    0
LAYER_TERRAIN = 1
LAYER_OBJECTS = 2

# Terrain
WATER = 'w'
PLAINS = 'p'
DIRT = 'd'
FOREST = 'f'
BEACH = 'b'
ROCK = 'r'
ICE = 'i'
HILL = 'h'
MOUNTAIN = 'm'
SWAMP = 's'
JUNGLE = 'j'
DESERT = 'd'
LAVA = 'l'
AIR = 'a'
UNDERGROUND = 'u'
SPACE = 'e'
CAVE = 'c'
TERRAIN_UNWALKABLE = [WATER, ROCK]
TERRAIN_ALL = [WATER, PLAINS, DIRT, FOREST]

# Player
SCROLL_TOP = CAMERA_SIZE[1]/3
SCROLL_BOTTOM = CAMERA_SIZE[1] - (CAMERA_SIZE[1]/3)
SCROLL_LEFT = CAMERA_SIZE[0]/3
SCROLL_RIGHT = CAMERA_SIZE[0] - (CAMERA_SIZE[0]/3)
ENCOUNTER_SPACES = 5
CHECK_SPACES_NORMAL = 2
CHECK_SPACES_DANGER = 1
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 48
PLAYER_WALK_SPEED = 2
PLAYER_WALK_ANIMATION_SPEED = 6
PLAYER_COLLIDE_SIZE = [ 11, 11 ]
PLAYER_COLLIDE_OFFSET = [ 11, -1 ]

# Monsters
MAX_MONSTERS = 4
