import pygame
from pygame.locals import *
from config import *

# Display
CAMERA_SIZE = [ WINDOW_SIZE[0], WINDOW_SIZE[1] ]

# Events
BATTLE_EVENT = pygame.USEREVENT + 1

# Interface
DIALOG_SIZE = (478,192)

# Map
TILE_IMAGE = 0
TILE_WALKABLE = 1
TILE_SLICE = 2
TILE_SIZE = 3
TILE_POS = 4

# Layers:
LAYER_DATA =    0
LAYER_TERRAIN = 1
LAYER_OBJECTS = 2

# Terrain
TERRAIN_CAVE_CEILING = [ 'c' ]
TERRAIN_CAVE_FLOOR = [ 'F' ]
TERRAIN_GRASS = [ 'g', 'g2', 'g3' ]
TERRAIN_FOREST = [ 'f' ]
TERRAIN_ALL_CAVE = [TERRAIN_CAVE_CEILING, TERRAIN_CAVE_FLOOR]
TERRAIN_ALL_WORLD = [TERRAIN_GRASS, TERRAIN_FOREST]
TERRAIN_TRANSITIONS = [
    TERRAIN_CAVE_FLOOR[0],
    TERRAIN_GRASS[1],
    TERRAIN_GRASS[2],
    TERRAIN_FOREST[0] ]
TERRAIN_UNWALKABLE = []
TERRAIN_RANDOMNESS = 5

# Player
PLAYER_SCROLL_TOP = CAMERA_SIZE[1]/3
PLAYER_SCROLL_BOTTOM = CAMERA_SIZE[1] - (CAMERA_SIZE[1]/3)
PLAYER_SCROLL_LEFT = CAMERA_SIZE[0]/3
PLAYER_SCROLL_RIGHT = CAMERA_SIZE[0] - (CAMERA_SIZE[0]/3)
PLAYER_MOVEMENT_NORMAL = 3
PLAYER_MOVEMENT_DANGER = 1
PLAYER_ENCOUNTER_ROLL = 3
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 48
PLAYER_WALK_SPEED = 2
PLAYER_WALK_ANIMATION_SPEED = 6
PLAYER_COLLIDE_SIZE = [ 11, 11 ]
PLAYER_COLLIDE_OFFSET = [ 11, -1 ]

# Monsters
MONSTERS_MAX_AMOUNT = 4
